name: Code Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/pricena-scraper:latest .
          docker push ghcr.io/${{ github.repository }}/pricena-scraper:latest

      - name: Run Prettier check
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/pricena-scraper:latest pnpm format:check

      - name: Run ESLint
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/pricena-scraper:latest pnpm lint

      - name: Run TypeScript type check
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/pricena-scraper:latest pnpm tsc --noEmit

      - name: Run tests
        run: |
          echo "Running tests..."
          docker run --rm ghcr.io/${{ github.repository }}/pricena-scraper:latest pnpm test || echo "Tests failed, but continuing due to continue-on-error"
        continue-on-error: true

      - name: Upload test coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage/
