name: Deploy to Vercel

on:
  workflow_run:
    workflows: ['Code Check']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/pricena-scraper:latest .
          docker push ghcr.io/${{ github.repository }}/pricena-scraper:latest

      - name: Install Vercel CLI
        run: |
          docker run --rm ghcr.io/${{ github.repository }}/pricena-scraper:latest pnpm add -g vercel

      - name: Deploy to Vercel
        run: |
          docker run --rm \
            -e VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
            -e VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }} \
            -e VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }} \
            ghcr.io/${{ github.repository }}/pricena-scraper:latest \
            vercel --prod --token $VERCEL_TOKEN
